# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mozeidon < Formula
  desc ""
  homepage "https://github.com/egovelox/mozeidon"
  version "1.0.0"

  on_macos do
    url "https://github.com/egovelox/mozeidon/releases/download/v1.0.0/mozeidon-cli_Darwin_all.tar.gz"
    sha256 "15508f42a7a7a84383c18bc783f30100c17ed4f7d38fbd4427073a327b4d0c02"

    def install
      bin.install "mozeidon-cli"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/egovelox/mozeidon/releases/download/v1.0.0/mozeidon-cli_Linux_arm64.tar.gz"
      sha256 "cf06c755e125bea5d4dca5f3c22a2b121af918a823d08d0572742b4d139cd321"

      def install
        bin.install "mozeidon-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/egovelox/mozeidon/releases/download/v1.0.0/mozeidon-cli_Linux_x86_64.tar.gz"
      sha256 "c8ad2d63b444a19b4481571c41a02adb0d2ba1bc74e74c39181c0d7214d74dbb"

      def install
        bin.install "mozeidon-cli"
      end
    end
  end
end
