# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MozeidonCli < Formula
  desc ""
  homepage "https://github.com/egovelox/mozeidon"
  version "1.0.0"

  on_macos do
    url "https://github.com/egovelox/mozeidon/releases/download/v1.0.0/mozeidon-cli_Darwin_all.tar.gz"
    sha256 "f057385a45861dcd06a9b40927be933c5b670ae0fbe1495beabd0884304a0d1f"

    def install
      bin.install "mozeidon-cli"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/egovelox/mozeidon/releases/download/v1.0.0/mozeidon-cli_Linux_arm64.tar.gz"
      sha256 "53fe43ff83ffb5e36384246280cfb8ec60d2adc7cdb7357b4daac74ef73747bd"

      def install
        bin.install "mozeidon-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/egovelox/mozeidon/releases/download/v1.0.0/mozeidon-cli_Linux_x86_64.tar.gz"
      sha256 "599a9e504a5ecb85a8a4f862521a0d503b227a3f4a216ae75f06c61f52b73b6e"

      def install
        bin.install "mozeidon-cli"
      end
    end
  end
end
