# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mozeidon < Formula
  desc ""
  homepage "https://github.com/egovelox/mozeidon"
  version "2.0.0"

  on_macos do
    url "https://github.com/egovelox/mozeidon/releases/download/v2.0.0/mozeidon_Darwin_all.tar.gz"
    sha256 "093144ebe0be734d42aea2ceaea436ca96cb1acf679ded2cdc18e1a3f92a0328"

    def install
      bin.install "mozeidon"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/egovelox/mozeidon/releases/download/v2.0.0/mozeidon_Linux_x86_64.tar.gz"
        sha256 "5d786dddb74b18f87aa5ac3e01bd96ae7bfbbcb73b6f50add1c6ec782ba246f2"

        def install
          bin.install "mozeidon"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/egovelox/mozeidon/releases/download/v2.0.0/mozeidon_Linux_arm64.tar.gz"
        sha256 "d7b8ec81b49cec6e4da02f645def8119c999bc02b125f09da17d3aa023388505"

        def install
          bin.install "mozeidon"
        end
      end
    end
  end
end
