# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MozeidonNativeApp < Formula
  desc ""
  homepage "https://github.com/egovelox/mozeidon-native-app"
  version "1.0.0"

  on_macos do
    url "https://github.com/egovelox/mozeidon-native-app/releases/download/v1.0.0/mozeidon-native-app_Darwin_all.tar.gz"
    sha256 "e0af9d39b6aae6d2364ac5277d1d522578e9448ff37c631291fc001b47dba3a6"

    def install
      bin.install "mozeidon-native-app"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/egovelox/mozeidon-native-app/releases/download/v1.0.0/mozeidon-native-app_Linux_arm64.tar.gz"
      sha256 "fe35f08b70c2872d2a5ca734be67de41eb52090944929e8198547ffa31291c77"

      def install
        bin.install "mozeidon-native-app"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/egovelox/mozeidon-native-app/releases/download/v1.0.0/mozeidon-native-app_Linux_x86_64.tar.gz"
      sha256 "b70b64b2d7bf0ccffbf605a93723e4c9ff2e53ee544e1db7a1ee803bb1758edb"

      def install
        bin.install "mozeidon-native-app"
      end
    end
  end
end
